services:
  mysql-db:
    restart: always
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  eureka-server:
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  config-server:
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  clientes-service:
    restart: always
    build:
      context: ./clientes-service
      dockerfile: Dockerfile
    container_name: clientes-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_clientes?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started

  pagos-service:
    restart: always
    build:
      context: ./pagos-service
      dockerfile: Dockerfile
    container_name: pagos-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_pagos?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
      clientes-service:
        condition: service_started

  facturas-service:
    restart: always
    build:
      context: ./facturas-service
      dockerfile: Dockerfile
    container_name: facturas-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_facturas?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  financiamiento-service:
    restart: always
    build:
      context: ./financiamiento-service
      dockerfile: Dockerfile
    container_name: financiamiento-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/financiamiento?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  inventario-service:
    restart: always
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    container_name: inventario-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_inventario?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  pedidos-service:
    restart: always
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile
    container_name: pedidos-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_pedidos?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  servicios-service:
    restart: always
    build:
      context: ./servicios-service
      dockerfile: Dockerfile
    container_name: servicios-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_servicios?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  sucursales-service:
    restart: always
    build:
      context: ./sucursales-service
      dockerfile: Dockerfile
    container_name: sucursales-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_sucursales?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  vehiculos-service:
    restart: always
    build:
      context: ./vehiculos-service
      dockerfile: Dockerfile
    container_name: vehiculos-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_vehiculos?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  vendedores-service:
    restart: always
    build:
      context: ./vendedores-service
      dockerfile: Dockerfile
    container_name: vendedores-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bd_vendedores?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db
      - eureka-server
      - config-server

  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - clientes-service
      - pagos-service
      - facturas-service
      - financiamiento-service
      - inventario-service
      - pedidos-service
      - servicios-service
      - sucursales-service
      - vehiculos-service
      - vendedores-service

volumes:
  mysql_data: