spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=clientes-service
spring.cloud.gateway.routes[0].uri=lb://clientes-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/clientes/**

spring.cloud.gateway.routes[1].id=vehiculos-service
spring.cloud.gateway.routes[1].uri=lb://vehiculos-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/vehiculos/**

spring.cloud.gateway.routes[2].id=sucursales-service
spring.cloud.gateway.routes[2].uri=lb://sucursales-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/sucursales/**

spring.cloud.gateway.routes[3].id=vendedores-service
spring.cloud.gateway.routes[3].uri=lb://vendedores-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/vendedores/**

spring.cloud.gateway.routes[4].id=pagos-service
spring.cloud.gateway.routes[4].uri=lb://pagos-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/pagos/**

spring.cloud.gateway.routes[5].id=financiamiento-service
spring.cloud.gateway.routes[5].uri=lb://financiamiento-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/financiamiento/**

spring.cloud.gateway.routes[6].id=pedidos-service
spring.cloud.gateway.routes[6].uri=lb://pedidos-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/pedidos/**

spring.cloud.gateway.routes[7].id=inventario-service
spring.cloud.gateway.routes[7].uri=lb://inventario-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/inventario/**

spring.cloud.gateway.routes[8].id=servicios-service
spring.cloud.gateway.routes[8].uri=lb://servicios-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/servicios/**

spring.cloud.gateway.routes[9].id=facturas-service
spring.cloud.gateway.routes[9].uri=lb://facturas-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/facturas/**
