spring:
  application:
    name: facturas-service
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
